### ISSUE TITLE
ResultsComparer build is broken

### ISSUE THREAD

**Issue by filipnavara** [dotnet/performance#1271]
Getting the following errors since April 07, 2020:

```
2020-04-07T11:49:12.9453125Z Program.cs(14,35): error CS0234: The type or namespace name 'StatisticalTesting' does not exist in the namespace 'BenchmarkDotNet.Mathematics' (are you missing an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9464548Z Program.cs(64,174): error CS0246: The type or namespace name 'Threshold' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9466593Z Program.cs(64,199): error CS0246: The type or namespace name 'Threshold' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9468606Z Program.cs(64,92): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9470542Z Program.cs(84,98): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9472376Z Program.cs(114,96): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9474267Z Program.cs(114,145): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9476146Z Program.cs(170,97): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9478017Z Program.cs(190,97): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9480011Z Program.cs(265,96): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
2020-04-07T11:49:12.9482402Z Program.cs(267,40): error CS0246: The type or namespace name 'EquivalenceTestConclusion' could not be found (are you missing a using directive or an assembly reference?) [/home/ubuntu/agent/_work/1/s/work/performance/src/tools/ResultsComparer/ResultsComparer.csproj]
```

The last successful build was from day before that.

**Comment by filipnavara** [comment]
Likely broken with PR #1269 that bumped to newer BDN version.
