### ISSUE TITLE
[main][runtime] iOS app builds are failing

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2924]
iOS app builds for mono testing are failing to build resulting in the iOS testing jobs not being run. An example failure is available here: https://dev.azure.com/dnceng/internal/_build/results?buildId=2130635&view=results under 'ios-arm64 release iOSMono'-> 'Build HelloiOS AOT Sample...'. The main failure seems to be 'ld: symbol(s) not found for architecture arm64', with full output available following the above steps (too large to put in github comment).

cc: @SamMonoRT, are you aware of any recent changes that may be causing this or someone that would have an idea?

**Comment by SamMonoRT** [comment]
@steveisok @akoeplinger - any known issues with iOS apps ?

**Comment by steveisok** [comment]
This regressed likely because of https://github.com/dotnet/runtime/pull/81919. It shifted where the gss framework got linked in and needs changed.  I'll put up a fix.
